### ISSUE TITLE
Line breaks in content not visible on event page.

### ISSUE THREAD

**Issue by rathorevaibhav** [Shubham2301/phase2#28]
Dashboard:
![image](https://cloud.githubusercontent.com/assets/12053186/26670864/03cd216c-46d1-11e7-8d9a-d0d0f6c5d2eb.png)

Event page:
![image](https://cloud.githubusercontent.com/assets/12053186/26670870/0db08200-46d1-11e7-8a27-6f50662b2c9c.png)

**Comment by Shubham2301** [comment]
<img width="973" alt="screen shot 2017-06-01 at 11 46 46 pm" src="https://cloud.githubusercontent.com/assets/26692825/26694447/0beae362-4725-11e7-82c6-585cd314f672.png">

<img width="899" alt="screen shot 2017-06-01 at 11 47 04 pm" src="https://cloud.githubusercontent.com/assets/26692825/26694468/1c72bf3e-4725-11e7-96fd-ccae42707697.png">
